USE [master]
GO

/****** Objeto: Database [GestionEmpleadosDB] Fecha de script: 02/05/2026 01:59:56 a. m. ******/
CREATE DATABASE [GestionEmpleadosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionEmpleadosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GestionEmpleadosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionEmpleadosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GestionEmpleadosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionEmpleadosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GestionEmpleadosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GestionEmpleadosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GestionEmpleadosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GestionEmpleadosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GestionEmpleadosDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GestionEmpleadosDB] SET  MULTI_USER 
GO

ALTER DATABASE [GestionEmpleadosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GestionEmpleadosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GestionEmpleadosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GestionEmpleadosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GestionEmpleadosDB] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [GestionEmpleadosDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GestionEmpleadosDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [GestionEmpleadosDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GestionEmpleadosDB] SET  READ_WRITE 
GO


